name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=TARBALL::grammarly-focal-${GITHUB_REF#refs/tags/}.tgz
      - name: Checkout code
        uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn package
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./packages/focal/${{ steps.branch_name.outputs.TARBALL }}
          asset_name: ${{ steps.branch_name.outputs.TARBALL }}
          tag: ${{ github.ref }}
